"""created endpoint, role and access table and updated user table

Revision ID: 285ca1794fc2
Revises: 4e9b62fc739a
Create Date: 2024-08-04 15:48:56.754296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285ca1794fc2'
down_revision = '4e9b62fc739a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('route', sa.String(length=120), nullable=True),
    sa.Column('method', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('method'),
    sa.UniqueConstraint('route')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_table('access')
    op.drop_table('role')
    op.drop_table('endpoint')
    # ### end Alembic commands ###
