"""updated Endpoint Table

Revision ID: 32fdae251b6c
Revises: 782356938191
Create Date: 2024-08-05 12:50:01.816675

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32fdae251b6c'
down_revision = '782356938191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('endpoint', 'roles',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)
    op.drop_constraint('endpoint_method_key', 'endpoint', type_='unique')
    op.alter_column('user', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('endpoint_method_key', 'endpoint', ['method'])
    op.alter_column('endpoint', 'roles',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True)
    # ### end Alembic commands ###
