"""updated book table

Revision ID: 6fcad3990914
Revises: 803ea30df098
Create Date: 2024-07-31 12:06:09.780594

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6fcad3990914"
down_revision = "803ea30df098"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book", "available_quantity", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("book", "status")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book",
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "book", "available_quantity", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
