"""update roles column  to integer

Revision ID: 77c41ec23e41
Revises: e0e44d5175ef
Create Date: 2024-08-05 14:09:05.131306

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77c41ec23e41'
down_revision = 'e0e44d5175ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'endpoint', 'role', ['role_id'], ['id'])
    op.drop_column('endpoint', 'roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint', sa.Column('roles', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'endpoint', type_='foreignkey')
    op.drop_column('endpoint', 'role_id')
    # ### end Alembic commands ###
