"""removed access table

Revision ID: 782356938191
Revises: 285ca1794fc2
Create Date: 2024-08-04 17:46:48.786782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '782356938191'
down_revision = '285ca1794fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access')
    op.add_column('endpoint', sa.Column('roles', sa.ARRAY(sa.Integer()), nullable=True))
    op.alter_column('user', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('endpoint', 'roles')
    op.create_table('access',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('endpoint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoint.id'], name='access_endpoint_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='access_pkey')
    )
    # ### end Alembic commands ###
