"""changed route to Unique=False 

Revision ID: 7d6b64055e95
Revises: 77c41ec23e41
Create Date: 2024-08-05 14:25:51.474432

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7d6b64055e95'
down_revision = '77c41ec23e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('endpoint_route_key', 'endpoint', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('endpoint_route_key', 'endpoint', ['route'])
    # ### end Alembic commands ###
